/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.GerenciadorUsuarios;
import javax.swing.JOptionPane;
import modelo.Aluno;
import modelo.Funcionario;
import modelo.Professor;
import modelo.UserExterno;
import modelo.Usuario;

/**
 *
 *
 */
public class TelaCadastroUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public TelaCadastroUsuario() {
        initComponents();
        jCtipoUsu.setSelectedItem("");
        btAtualizarUsu.setEnabled(false);
        btExcluirUsu.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTituloCadastroUsu = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbEnderecoUsu = new javax.swing.JLabel();
        tfCPFUsu = new javax.swing.JTextField();
        tfNomeUsu = new javax.swing.JTextField();
        tfEndUsu = new javax.swing.JTextField();
        btBuscarUsu = new javax.swing.JButton();
        lbDataNascUsu = new javax.swing.JLabel();
        lbSenhaoUsu = new javax.swing.JLabel();
        lbFoneUsu = new javax.swing.JLabel();
        lbEmailUsu = new javax.swing.JLabel();
        lbCPFUsu = new javax.swing.JLabel();
        lbTipoUsu = new javax.swing.JLabel();
        jCtipoUsu = new javax.swing.JComboBox<>();
        tfEmailUsu = new javax.swing.JTextField();
        lbNomeUsu = new javax.swing.JLabel();
        tfDataNascUsu = new javax.swing.JFormattedTextField();
        tfFoneUsu = new javax.swing.JFormattedTextField();
        tfSenhaUsu = new javax.swing.JPasswordField();
        jPBotoes = new javax.swing.JPanel();
        btExcluirUsu = new javax.swing.JButton();
        btAtualizarUsu = new javax.swing.JButton();
        btSalvarUsu = new javax.swing.JButton();
        btLimparUso = new javax.swing.JButton();
        jPdadosEspec = new javax.swing.JPanel();
        lbCursoUsu = new javax.swing.JLabel();
        lbCargoUsu = new javax.swing.JLabel();
        lbPagamentoUsu = new javax.swing.JLabel();
        tfCursoUsu = new javax.swing.JTextField();
        tfCargoUsu = new javax.swing.JTextField();
        lbMatriculaUsu = new javax.swing.JLabel();
        tfMatriculaUsu = new javax.swing.JTextField();
        tfdepartamentoUsu = new javax.swing.JTextField();
        lbDepartamentoUsu = new javax.swing.JLabel();
        tfpagamentoUsu = new javax.swing.JTextField();

        setClosable(true);

        lbTituloCadastroUsu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTituloCadastroUsu.setText("Cadastro de Usuários");

        lbEnderecoUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbEnderecoUsu.setText("Endereço:");

        tfCPFUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tfNomeUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfNomeUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeUsuActionPerformed(evt);
            }
        });

        tfEndUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btBuscarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search-12-16_1.png"))); // NOI18N
        btBuscarUsu.setPreferredSize(new java.awt.Dimension(23, 23));
        btBuscarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarUsuActionPerformed(evt);
            }
        });

        lbDataNascUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDataNascUsu.setText("Data de nascimento:");

        lbSenhaoUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbSenhaoUsu.setText("Senha:");

        lbFoneUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbFoneUsu.setText("Fone:");

        lbEmailUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbEmailUsu.setText("E-mail:");

        lbCPFUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCPFUsu.setText("CPF:");

        lbTipoUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTipoUsu.setText("Tipo:");

        jCtipoUsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aluno", "Funcionário", "Professor", "Externo", "" }));
        jCtipoUsu.setToolTipText("");
        jCtipoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCtipoUsuActionPerformed(evt);
            }
        });

        tfEmailUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfEmailUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailUsuActionPerformed(evt);
            }
        });

        lbNomeUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNomeUsu.setText("Nome:");

        try {
            tfDataNascUsu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataNascUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataNascUsuActionPerformed(evt);
            }
        });

        try {
            tfFoneUsu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfFoneUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFoneUsuActionPerformed(evt);
            }
        });

        tfSenhaUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSenhaUsuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSenhaoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbCPFUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbEnderecoUsu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbFoneUsu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lbNomeUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbEmailUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfEndUsu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfFoneUsu)
                                    .addComponent(tfCPFUsu, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbDataNascUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbTipoUsu)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCtipoUsu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfDataNascUsu)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tfEmailUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btBuscarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfNomeUsu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(tfSenhaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEmailUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEmailUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNomeUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNomeUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btBuscarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCPFUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCPFUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDataNascUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDataNascUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfFoneUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTipoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbFoneUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCtipoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEnderecoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEndUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSenhaoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSenhaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lbTituloCadastroUsu))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTituloCadastroUsu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );

        btExcluirUsu.setBackground(new java.awt.Color(255, 0, 0));
        btExcluirUsu.setForeground(new java.awt.Color(255, 255, 255));
        btExcluirUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete-24_1.png"))); // NOI18N
        btExcluirUsu.setText("Excluir");
        btExcluirUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirUsuActionPerformed(evt);
            }
        });

        btAtualizarUsu.setBackground(new java.awt.Color(255, 153, 0));
        btAtualizarUsu.setForeground(new java.awt.Color(255, 255, 255));
        btAtualizarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/refresh-24_1.png"))); // NOI18N
        btAtualizarUsu.setText("Atualizar");
        btAtualizarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarUsuActionPerformed(evt);
            }
        });

        btSalvarUsu.setBackground(new java.awt.Color(50, 150, 0));
        btSalvarUsu.setForeground(new java.awt.Color(255, 255, 255));
        btSalvarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save-24_1.png"))); // NOI18N
        btSalvarUsu.setText("Salvar");
        btSalvarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarUsuActionPerformed(evt);
            }
        });

        btLimparUso.setBackground(new java.awt.Color(0, 153, 255));
        btLimparUso.setForeground(new java.awt.Color(255, 255, 255));
        btLimparUso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar-24.png"))); // NOI18N
        btLimparUso.setText("Limpar");
        btLimparUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparUsoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBotoesLayout = new javax.swing.GroupLayout(jPBotoes);
        jPBotoes.setLayout(jPBotoesLayout);
        jPBotoesLayout.setHorizontalGroup(
            jPBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBotoesLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btSalvarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btLimparUso, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btAtualizarUsu)
                .addGap(35, 35, 35)
                .addComponent(btExcluirUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPBotoesLayout.setVerticalGroup(
            jPBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBotoesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvarUsu)
                    .addComponent(btAtualizarUsu)
                    .addComponent(btExcluirUsu)
                    .addComponent(btLimparUso))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        lbCursoUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCursoUsu.setText("Curso:");

        lbCargoUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCargoUsu.setText("Cargo:");

        lbPagamentoUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbPagamentoUsu.setText("Pagamento:");

        tfCursoUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfCursoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCursoUsuActionPerformed(evt);
            }
        });

        tfCargoUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfCargoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCargoUsuActionPerformed(evt);
            }
        });

        lbMatriculaUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbMatriculaUsu.setText("Matrícula:");

        tfMatriculaUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfMatriculaUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMatriculaUsuActionPerformed(evt);
            }
        });

        tfdepartamentoUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfdepartamentoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdepartamentoUsuActionPerformed(evt);
            }
        });

        lbDepartamentoUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDepartamentoUsu.setText("Departamento:");

        tfpagamentoUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfpagamentoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpagamentoUsuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPdadosEspecLayout = new javax.swing.GroupLayout(jPdadosEspec);
        jPdadosEspec.setLayout(jPdadosEspecLayout);
        jPdadosEspecLayout.setHorizontalGroup(
            jPdadosEspecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPdadosEspecLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPdadosEspecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbPagamentoUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPdadosEspecLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPdadosEspecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbCargoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCursoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPdadosEspecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPdadosEspecLayout.createSequentialGroup()
                        .addGroup(jPdadosEspecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfCursoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCargoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPdadosEspecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDepartamentoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMatriculaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPdadosEspecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfMatriculaUsu, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(tfdepartamentoUsu))
                        .addGap(22, 22, 22))
                    .addGroup(jPdadosEspecLayout.createSequentialGroup()
                        .addComponent(tfpagamentoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPdadosEspecLayout.setVerticalGroup(
            jPdadosEspecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPdadosEspecLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(jPdadosEspecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMatriculaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMatriculaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCursoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCursoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPdadosEspecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDepartamentoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdepartamentoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCargoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCargoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPdadosEspecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPagamentoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfpagamentoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jPdadosEspec, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPdadosEspec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeUsuActionPerformed

    private void btBuscarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarUsuActionPerformed
        // TODO add your handling code here:

        String email = tfEmailUsu.getText();
        GerenciadorUsuarios gerenciadorUsu = GerenciadorUsuarios.getInstance();
        Usuario user = gerenciadorUsu.buscarUsuario(email);
        if (user == (null)) {
            JOptionPane.showMessageDialog(null, "Não encontrado!");

        } else {
            btAtualizarUsu.setEnabled(true);
            btExcluirUsu.setEnabled(true);
            String tipodeusuario = jCtipoUsu.getSelectedItem().toString();
            if (user instanceof Aluno) {
                Aluno aluno = (Aluno) user;
                this.tfCursoUsu.setEnabled(true);
                this.tfMatriculaUsu.setEnabled(true);
                String nome = aluno.getNome();
                String cpf = aluno.getCpf();
                String telefone = aluno.getTelefone();
                String endereco = aluno.getEndereco();
                String senha = aluno.getSenha();
                String nascimento = aluno.getNascimento();
                String curso = aluno.getCurso();
                String matricula = aluno.getMatricula();
                tfNomeUsu.setText(nome);
                tfFoneUsu.setText(telefone);
                tfSenhaUsu.setText(senha);
                tfCPFUsu.setText(cpf);
                tfDataNascUsu.setText(nascimento);
                tfCursoUsu.setText(curso);
                tfMatriculaUsu.setText(matricula);
                tfEndUsu.setText(endereco);
                jCtipoUsu.setSelectedItem("Aluno");
                tfdepartamentoUsu.setEnabled(false);
                tfCargoUsu.setEnabled(false);
                tfpagamentoUsu.setEnabled(false);

            } else if (user instanceof Professor) {
                Professor professor = (Professor) user;
                this.tfdepartamentoUsu.setEnabled(true);
                String nome = professor.getNome();
                String cpf = professor.getCpf();
                String telefone = professor.getTelefone();
                String endereco = professor.getEndereco();
                String senha = professor.getSenha();
                String nascimento = professor.getNascimento();
                String departamento = professor.getDepartamento();
                tfNomeUsu.setText(nome);
                tfFoneUsu.setText(telefone);
                tfSenhaUsu.setText(senha);
                tfCPFUsu.setText(cpf);
                tfDataNascUsu.setText(nascimento);
                tfdepartamentoUsu.setText(departamento);
                tfEndUsu.setText(endereco);
                jCtipoUsu.setSelectedItem("Professor");
                tfCargoUsu.setEnabled(false);
                tfpagamentoUsu.setEnabled(false);
                tfCursoUsu.setEnabled(false);
                tfMatriculaUsu.setEnabled(false);

            } else if (user instanceof Funcionario) {
                Funcionario funcionario = (Funcionario) user;
                this.tfCargoUsu.setEnabled(true);
                String nome = funcionario.getNome();
                String cpf = funcionario.getCpf();
                String telefone = funcionario.getTelefone();
                String endereco = funcionario.getEndereco();
                String senha = funcionario.getSenha();
                String nascimento = funcionario.getNascimento();
                String cargo = funcionario.getCargo();
                tfNomeUsu.setText(nome);
                tfFoneUsu.setText(telefone);
                tfSenhaUsu.setText(senha);
                tfCPFUsu.setText(cpf);
                tfDataNascUsu.setText(nascimento);
                tfCargoUsu.setText(cargo);
                tfEndUsu.setText(endereco);
                jCtipoUsu.setSelectedItem("Funcionário");
                tfdepartamentoUsu.setEnabled(false);
                tfpagamentoUsu.setEnabled(false);
                tfCursoUsu.setEnabled(false);
                tfMatriculaUsu.setEnabled(false);

            } else if (user instanceof UserExterno) {
                UserExterno externo = (UserExterno) user;
                this.tfpagamentoUsu.setEnabled(true);
                String nome = externo.getNome();
                String cpf = externo.getCpf();
                String telefone = externo.getTelefone();
                String endereco = externo.getEndereco();
                String senha = externo.getSenha();
                String nascimento = externo.getNascimento();
                String pagamento = externo.getMensalidade();
                tfNomeUsu.setText(nome);
                tfFoneUsu.setText(telefone);
                tfSenhaUsu.setText(senha);
                tfCPFUsu.setText(cpf);
                tfDataNascUsu.setText(nascimento);
                tfpagamentoUsu.setText(pagamento);
                tfEndUsu.setText(endereco);
                jCtipoUsu.setSelectedItem("Externo");
                tfdepartamentoUsu.setEnabled(false);
                tfCargoUsu.setEnabled(false);
                tfCursoUsu.setEnabled(false);
                tfMatriculaUsu.setEnabled(false);

            }
        }

    }//GEN-LAST:event_btBuscarUsuActionPerformed

    private void jCtipoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCtipoUsuActionPerformed
        // TODO add your handling code here:
        String tipodeusuario = jCtipoUsu.getSelectedItem().toString();
        if (tipodeusuario.equals("Aluno")) {
            this.tfdepartamentoUsu.setEnabled(false);
            this.tfCargoUsu.setEnabled(false);
            this.tfpagamentoUsu.setEnabled(false);
            this.tfCursoUsu.setEnabled(true);
            this.tfMatriculaUsu.setEnabled(true);
        } else if (tipodeusuario.equals("Professor")) {
            this.tfdepartamentoUsu.setEnabled(true);
            this.tfCargoUsu.setEnabled(false);
            this.tfpagamentoUsu.setEnabled(false);
            this.tfCursoUsu.setEnabled(false);
            this.tfMatriculaUsu.setEnabled(false);

        } else if (tipodeusuario.equals("Funcionário")) {
            this.tfdepartamentoUsu.setEnabled(false);
            this.tfCargoUsu.setEnabled(true);
            this.tfpagamentoUsu.setEnabled(false);
            this.tfCursoUsu.setEnabled(false);
            this.tfMatriculaUsu.setEnabled(false);
        } else if (tipodeusuario.equals("Externo")) {
            this.tfdepartamentoUsu.setEnabled(false);
            this.tfCargoUsu.setEnabled(false);
            this.tfpagamentoUsu.setEnabled(true);
            this.tfCursoUsu.setEnabled(false);
            this.tfMatriculaUsu.setEnabled(false);

        }

    }//GEN-LAST:event_jCtipoUsuActionPerformed

    private void tfEmailUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailUsuActionPerformed

    private void tfDataNascUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataNascUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataNascUsuActionPerformed

    private void tfFoneUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFoneUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFoneUsuActionPerformed

    private void tfSenhaUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSenhaUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSenhaUsuActionPerformed

    private void btExcluirUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirUsuActionPerformed
        // TODO add your handling code here:
        btExcluirUsu.setEnabled(false);
        btAtualizarUsu.setEnabled(false);
        String email = tfEmailUsu.getText();
        GerenciadorUsuarios gerenciadorUsu = GerenciadorUsuarios.getInstance();
        boolean usuarioRemover = gerenciadorUsu.removerUsuario(email);
        if (usuarioRemover == false) {
            JOptionPane.showMessageDialog(null, "Não encontrado!");
        } else {
            JOptionPane.showMessageDialog(null, "Usuário removido com sucesso!");

        }
        tfEmailUsu.setText("");
        tfNomeUsu.setText("");
        tfFoneUsu.setText("");
        tfSenhaUsu.setText("");
        tfCPFUsu.setText("");
        tfDataNascUsu.setText("");
        tfEndUsu.setText("");
        tfCursoUsu.setText("");
        tfMatriculaUsu.setText("");
        tfdepartamentoUsu.setText("");
        tfpagamentoUsu.setText("");
        tfCargoUsu.setText("");
        jCtipoUsu.setSelectedItem("");
    }//GEN-LAST:event_btExcluirUsuActionPerformed

    private void btAtualizarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarUsuActionPerformed
        // TODO add your handling code here:
        btAtualizarUsu.setEnabled(false);
        btExcluirUsu.setEnabled(false);
        String email = tfEmailUsu.getText();
        GerenciadorUsuarios gerenciadorUsu = GerenciadorUsuarios.getInstance();
        boolean usuarioRemover = gerenciadorUsu.removerUsuario(email);
        if (usuarioRemover == false) {
            JOptionPane.showMessageDialog(null, "Usuário não encontrado!");
        } else {
            String nome = tfNomeUsu.getText();
            if (nome.length() == 0) {
                JOptionPane.showMessageDialog(null, "Esqueceu de digitar o nome");
                return;
            }
            if (email.length() == 0) {
                JOptionPane.showMessageDialog(null, "Email em branco");
                return;
            }
            String cpf = tfCPFUsu.getText();
            if (cpf.length() == 0) {
                JOptionPane.showMessageDialog(null, "cpf em branco");
                return;
            }
            String fone = tfFoneUsu.getText();
            if (fone.length() == 0) {
                JOptionPane.showMessageDialog(null, "telefone em branco");
                return;
            }
            String endereco = tfEndUsu.getText();
            if (endereco.length() == 0) {
                JOptionPane.showMessageDialog(null, "Endereço vazio");
                return;
            }

            String senha = tfSenhaUsu.getText();
            if (senha.length() == 0) {
                JOptionPane.showMessageDialog(null, "Campo senha vazio");
                return;
            }

            String nascimento = tfDataNascUsu.getText();
            if (nascimento.length() == 0) {
                JOptionPane.showMessageDialog(null, "Campo data de nascimento vazio");
                return;
            }
            String tipodeusuario = jCtipoUsu.getSelectedItem().toString();
            if (tipodeusuario.equals("Aluno")) {
                String curso = tfCursoUsu.getText();
                if (curso.length() == 0) {
                    JOptionPane.showMessageDialog(null, "Campo curso vazio");
                    return;
                }
                String matricula = tfMatriculaUsu.getText();
                if (matricula.length() == 0) {
                    JOptionPane.showMessageDialog(null, "Campo matrícula vazio");
                    return;
                }
                Aluno aluno1 = new Aluno(curso, matricula, senha, nome, endereco, email, fone, nascimento, cpf);
                if (gerenciadorUsu.addUsuario(aluno1)) {
                    JOptionPane.showMessageDialog(null, "Usuário " + nome + " atualizado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Usuário já cadastrado com esse email e com esse perfil. Não foi possível editar");
                }

            } else if (tipodeusuario.equals("Professor")) {
                String departamento = tfdepartamentoUsu.getText();
                if (departamento.length() == 0) {
                    JOptionPane.showMessageDialog(null, "Campo departamento vazio");
                    return;
                }

                Professor prof1 = new Professor(departamento, senha, nome, endereco, email, fone, nascimento, cpf);
                if (gerenciadorUsu.addUsuario(prof1)) {
                    JOptionPane.showMessageDialog(null, "Usuário " + nome + " atualizado com sucesso!");

                } else {
                    JOptionPane.showMessageDialog(null, "Usuário já cadastrado com esse email e com esse perfil. Não foi possível editar");

                }
            } else if (tipodeusuario.equals("Funcionário")) {
                String cargo = tfCargoUsu.getText();
                if (cargo.length() == 0) {
                    JOptionPane.showMessageDialog(null, "Campo cargo vazio");
                    return;
                }
                Funcionario func1 = new Funcionario(cargo, senha, nome, endereco, email, fone, nascimento, cpf);
                if (gerenciadorUsu.addUsuario(func1)) {
                    JOptionPane.showMessageDialog(null, "Usuário " + nome + " atualizado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Usuário já cadastrado com esse email e com esse perfil. Não foi possível editar");

                }
            } else if (tipodeusuario.equals("Externo")) {
                String pagamento = tfpagamentoUsu.getText();
                if (pagamento.length() == 0) {
                    JOptionPane.showMessageDialog(null, "Campo pagamento vazio");
                    return;
                }
                UserExterno externo1 = new UserExterno(senha, nome, endereco, email, fone, nascimento, cpf, pagamento);
                if (gerenciadorUsu.addUsuario(externo1)) {
                    JOptionPane.showMessageDialog(null, "Usuário " + nome + " atualizado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Usuário já cadastrado com esse email e com esse perfil. Não foi possível editar");
                }
            }
        }

        tfEmailUsu.setText("");
        tfNomeUsu.setText("");
        tfFoneUsu.setText("");
        tfSenhaUsu.setText("");
        tfCPFUsu.setText("");
        tfDataNascUsu.setText("");
        tfEndUsu.setText("");
        tfCursoUsu.setText("");
        tfMatriculaUsu.setText("");
        tfdepartamentoUsu.setText("");
        tfpagamentoUsu.setText("");
        tfCargoUsu.setText("");
        jCtipoUsu.setSelectedItem("");
    }//GEN-LAST:event_btAtualizarUsuActionPerformed

    private void btSalvarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarUsuActionPerformed
        // TODO add your handling code here:
        String nome = tfNomeUsu.getText();
        if (nome.length() == 0) {
            JOptionPane.showMessageDialog(null, "Esqueceu de digitar o nome");
            return;
        }
        String email = tfEmailUsu.getText();
        if (email.length() == 0) {
            JOptionPane.showMessageDialog(null, "Email em branco");
            return;
        }
        String cpf = tfCPFUsu.getText();
        if (cpf.length() == 0) {
            JOptionPane.showMessageDialog(null, "cpf em branco");
            return;
        }
        String fone = tfFoneUsu.getText();
        if (fone.length() == 0) {
            JOptionPane.showMessageDialog(null, "telefone em branco");
            return;
        }
        String endereco = tfEndUsu.getText();
        if (endereco.length() == 0) {
            JOptionPane.showMessageDialog(null, "Endereço vazio");
            return;
        }

        String senha = tfSenhaUsu.getText();
        if (senha.length() == 0) {
            JOptionPane.showMessageDialog(null, "Campo senha vazio");
            return;
        }

        String nascimento = tfDataNascUsu.getText();
        if (nascimento.length() == 0) {
            JOptionPane.showMessageDialog(null, "Campo data de nascimento vazio");
            return;
        }
        String tipodeusuario = jCtipoUsu.getSelectedItem().toString();
        if (tipodeusuario.equals("Aluno")) {
            String curso = tfCursoUsu.getText();
            if (curso.length() == 0) {
                JOptionPane.showMessageDialog(null, "Campo curso vazio");
                return;
            }
            String matricula = tfMatriculaUsu.getText();
            if (matricula.length() == 0) {
                JOptionPane.showMessageDialog(null, "Campo matrícula vazio");
                return;
            }
            Aluno aluno1 = new Aluno(curso, matricula, senha, nome, endereco, email, fone, nascimento, cpf);
            GerenciadorUsuarios gerenciadorUsu = GerenciadorUsuarios.getInstance();
            if (gerenciadorUsu.addUsuario(aluno1)) {
                JOptionPane.showMessageDialog(null, "Usuário " + nome + " adicionado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Aluno já cadastrado com esse email");
            }

        } else if (tipodeusuario.equals("Professor")) {
            String departamento = tfdepartamentoUsu.getText();
            if (departamento.length() == 0) {
                JOptionPane.showMessageDialog(null, "Campo departamento vazio");
                return;
            }

            Professor prof1 = new Professor(departamento, senha, nome, endereco, email, fone, nascimento, cpf);
            GerenciadorUsuarios gerenciadorUsu = GerenciadorUsuarios.getInstance();
            if (gerenciadorUsu.addUsuario(prof1)) {
                JOptionPane.showMessageDialog(null, "Usuário " + nome + " adicionado com sucesso!");

            } else {
                JOptionPane.showMessageDialog(null, "Professor já cadastrado com esse email");

            }
        } else if (tipodeusuario.equals("Funcionário")) {
            String cargo = tfCargoUsu.getText();
            if (cargo.length() == 0) {
                JOptionPane.showMessageDialog(null, "Campo cargo vazio");
                return;
            }
            Funcionario func1 = new Funcionario(cargo, senha, nome, endereco, email, fone, nascimento, cpf);
            GerenciadorUsuarios gerenciadorUsu = GerenciadorUsuarios.getInstance();
            if (gerenciadorUsu.addUsuario(func1)) {
                JOptionPane.showMessageDialog(null, "Usuário " + nome + " adicionado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Funcionário já cadastrado com esse email");

            }
        } else if (tipodeusuario.equals("Externo")) {
            String pagamento = tfpagamentoUsu.getText();
            if (pagamento.length() == 0) {
                JOptionPane.showMessageDialog(null, "Campo pagamento vazio");
                return;
            }
            UserExterno externo1 = new UserExterno(senha, nome, endereco, email, fone, nascimento, cpf, pagamento);
            GerenciadorUsuarios gerenciadorUsu = GerenciadorUsuarios.getInstance();
            if (gerenciadorUsu.addUsuario(externo1)) {
                JOptionPane.showMessageDialog(null, "Usuário " + nome + " adicionado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Usuário já cadastrado com esse email");
            }
        }
        

        tfEmailUsu.setText("");
        tfNomeUsu.setText("");
        tfFoneUsu.setText("");
        tfSenhaUsu.setText("");
        tfCPFUsu.setText("");
        tfDataNascUsu.setText("");
        tfEndUsu.setText("");
        tfCursoUsu.setText("");
        tfMatriculaUsu.setText("");
        tfdepartamentoUsu.setText("");
        tfpagamentoUsu.setText("");
        tfCargoUsu.setText("");
        jCtipoUsu.setSelectedItem("");
    }//GEN-LAST:event_btSalvarUsuActionPerformed

    private void tfCursoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCursoUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCursoUsuActionPerformed

    private void tfCargoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCargoUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCargoUsuActionPerformed

    private void tfMatriculaUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMatriculaUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMatriculaUsuActionPerformed

    private void tfdepartamentoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdepartamentoUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdepartamentoUsuActionPerformed

    private void tfpagamentoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpagamentoUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpagamentoUsuActionPerformed

    private void btLimparUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparUsoActionPerformed
        // TODO add your handling code here:
        tfEmailUsu.setText("");
        tfNomeUsu.setText("");
        tfFoneUsu.setText("");
        tfSenhaUsu.setText("");
        tfCPFUsu.setText("");
        tfDataNascUsu.setText("");
        tfEndUsu.setText("");
        tfCursoUsu.setText("");
        tfMatriculaUsu.setText("");
        tfdepartamentoUsu.setText("");
        tfpagamentoUsu.setText("");
        tfCargoUsu.setText("");
        jCtipoUsu.setSelectedItem("");
        btAtualizarUsu.setEnabled(false);
        btExcluirUsu.setEnabled(false);
    }//GEN-LAST:event_btLimparUsoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizarUsu;
    private javax.swing.JButton btBuscarUsu;
    private javax.swing.JButton btExcluirUsu;
    private javax.swing.JButton btLimparUso;
    private javax.swing.JButton btSalvarUsu;
    private javax.swing.JComboBox<String> jCtipoUsu;
    private javax.swing.JPanel jPBotoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPdadosEspec;
    private javax.swing.JLabel lbCPFUsu;
    private javax.swing.JLabel lbCargoUsu;
    private javax.swing.JLabel lbCursoUsu;
    private javax.swing.JLabel lbDataNascUsu;
    private javax.swing.JLabel lbDepartamentoUsu;
    private javax.swing.JLabel lbEmailUsu;
    private javax.swing.JLabel lbEnderecoUsu;
    private javax.swing.JLabel lbFoneUsu;
    private javax.swing.JLabel lbMatriculaUsu;
    private javax.swing.JLabel lbNomeUsu;
    private javax.swing.JLabel lbPagamentoUsu;
    private javax.swing.JLabel lbSenhaoUsu;
    private javax.swing.JLabel lbTipoUsu;
    private javax.swing.JLabel lbTituloCadastroUsu;
    private javax.swing.JTextField tfCPFUsu;
    private javax.swing.JTextField tfCargoUsu;
    private javax.swing.JTextField tfCursoUsu;
    private javax.swing.JFormattedTextField tfDataNascUsu;
    private javax.swing.JTextField tfEmailUsu;
    private javax.swing.JTextField tfEndUsu;
    private javax.swing.JFormattedTextField tfFoneUsu;
    private javax.swing.JTextField tfMatriculaUsu;
    private javax.swing.JTextField tfNomeUsu;
    private javax.swing.JPasswordField tfSenhaUsu;
    private javax.swing.JTextField tfdepartamentoUsu;
    private javax.swing.JTextField tfpagamentoUsu;
    // End of variables declaration//GEN-END:variables
}
