/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.GerenciadorEspacos;
import controle.GerenciadorReservaEspaco;
import controle.GerenciadorUsuarios;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Espaco;
import modelo.Usuario;

/**
 *
 *
 */
public class TelaReservaEspaco extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaReservaEspaco
     */
    public TelaReservaEspaco() {
        initComponents();
        
        GerenciadorEspacos ge = GerenciadorEspacos.getInstance();
        ge.buscarEspaco("");
        
        cbEspacoEvento.addItem("...");
        ArrayList<Espaco> espacos = ge.getListaEspacos();
        for (int i = 0; i < espacos.size(); i++) {
            cbEspacoEvento.addItem(espacos.get(i).getDescEspaco());
        }
        GerenciadorUsuarios gr = GerenciadorUsuarios.getInstance();
        Usuario usuario = gr.getUsuarioLogado();
        tfRespResEsp.setText(usuario.getEmail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfDataEvt = new javax.swing.JFormattedTextField();
        lbDataEvt = new javax.swing.JLabel();
        tfHoraEvt = new javax.swing.JFormattedTextField();
        lbHoraEvt = new javax.swing.JLabel();
        btSalvarEvt = new javax.swing.JButton();
        btLimparEvt = new javax.swing.JButton();
        btExcluirEvt = new javax.swing.JButton();
        tfFoneEvt = new javax.swing.JFormattedTextField();
        lbFoneEvt = new javax.swing.JLabel();
        tfRespEvt = new javax.swing.JTextField();
        lbRespEvt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbDataResEsp = new javax.swing.JLabel();
        tfDataResEsp = new javax.swing.JFormattedTextField();
        lbHoraResEsp = new javax.swing.JLabel();
        tfHoraResEsp = new javax.swing.JFormattedTextField();
        btLimparResEsp = new javax.swing.JButton();
        btExcluirResEsp = new javax.swing.JButton();
        btSalvarResEsp = new javax.swing.JButton();
        lbRespResEsp = new javax.swing.JLabel();
        tfRespResEsp = new javax.swing.JTextField();
        tfDescricao = new javax.swing.JTextField();
        lbDescEsp = new javax.swing.JLabel();
        lbDescEsp1 = new javax.swing.JLabel();
        cbEspacoEvento = new javax.swing.JComboBox<>();
        lbTituloTelaResEsp = new javax.swing.JLabel();

        try {
            tfDataEvt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataEvt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbDataEvt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDataEvt.setText("Data");

        try {
            tfHoraEvt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfHoraEvt.setText("");
        tfHoraEvt.setToolTipText("");
        tfHoraEvt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbHoraEvt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbHoraEvt.setText("Hora");

        btSalvarEvt.setBackground(new java.awt.Color(50, 150, 0));
        btSalvarEvt.setForeground(new java.awt.Color(255, 255, 255));
        btSalvarEvt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete-24_1.png"))); // NOI18N
        btSalvarEvt.setText("Salvar");
        btSalvarEvt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarEvtActionPerformed(evt);
            }
        });

        btLimparEvt.setBackground(new java.awt.Color(255, 153, 0));
        btLimparEvt.setForeground(new java.awt.Color(255, 255, 255));
        btLimparEvt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/refresh-24_1.png"))); // NOI18N
        btLimparEvt.setText("Limpar");
        btLimparEvt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparEvtActionPerformed(evt);
            }
        });

        btExcluirEvt.setBackground(new java.awt.Color(255, 0, 0));
        btExcluirEvt.setForeground(new java.awt.Color(255, 255, 255));
        btExcluirEvt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete-24_1.png"))); // NOI18N
        btExcluirEvt.setText("Excluir");
        btExcluirEvt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirEvtActionPerformed(evt);
            }
        });

        try {
            tfFoneEvt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfFoneEvt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfFoneEvt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFoneEvtActionPerformed(evt);
            }
        });

        lbFoneEvt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbFoneEvt.setText("Fone");

        tfRespEvt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbRespEvt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbRespEvt.setText("Responsável");

        setClosable(true);

        lbDataResEsp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDataResEsp.setText("Data:");

        try {
            tfDataResEsp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataResEsp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbHoraResEsp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbHoraResEsp.setText("Hora");

        try {
            tfHoraResEsp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfHoraResEsp.setText("");
        tfHoraResEsp.setToolTipText("");
        tfHoraResEsp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btLimparResEsp.setBackground(new java.awt.Color(255, 153, 0));
        btLimparResEsp.setForeground(new java.awt.Color(255, 255, 255));
        btLimparResEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar-24.png"))); // NOI18N
        btLimparResEsp.setText("Limpar");
        btLimparResEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparResEspActionPerformed(evt);
            }
        });

        btExcluirResEsp.setBackground(new java.awt.Color(255, 0, 0));
        btExcluirResEsp.setForeground(new java.awt.Color(255, 255, 255));
        btExcluirResEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete-24_1.png"))); // NOI18N
        btExcluirResEsp.setText("Excluir");
        btExcluirResEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirResEspActionPerformed(evt);
            }
        });

        btSalvarResEsp.setBackground(new java.awt.Color(50, 150, 0));
        btSalvarResEsp.setForeground(new java.awt.Color(255, 255, 255));
        btSalvarResEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/today-24.png"))); // NOI18N
        btSalvarResEsp.setText("Reservar");
        btSalvarResEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarResEspActionPerformed(evt);
            }
        });

        lbRespResEsp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbRespResEsp.setText("Responsavel:");

        tfRespResEsp.setEditable(false);
        tfRespResEsp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tfDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbDescEsp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDescEsp.setText("Descrição:");

        lbDescEsp1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDescEsp1.setText("Espaço:");

        cbEspacoEvento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbEspacoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEspacoEventoActionPerformed(evt);
            }
        });

        lbTituloTelaResEsp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTituloTelaResEsp.setText("Reserva espaço");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTituloTelaResEsp)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbDescEsp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbDataResEsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(214, 214, 214)
                                        .addComponent(lbHoraResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(tfHoraResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbEspacoEvento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbRespResEsp)
                                    .addComponent(lbDescEsp))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfDescricao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                                        .addComponent(tfRespResEsp, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(tfDataResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btSalvarResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btLimparResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btExcluirResEsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lbTituloTelaResEsp)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEspacoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDescEsp1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDataResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfHoraResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHoraResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDataResEsp))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRespResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRespResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDescEsp))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimparResEsp)
                    .addComponent(btExcluirResEsp)
                    .addComponent(btSalvarResEsp))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarEvtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarEvtActionPerformed


    }//GEN-LAST:event_btSalvarEvtActionPerformed

    private void btLimparEvtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparEvtActionPerformed

    }//GEN-LAST:event_btLimparEvtActionPerformed

    private void btExcluirEvtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirEvtActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btExcluirEvtActionPerformed

    private void tfFoneEvtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFoneEvtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFoneEvtActionPerformed

    private void btSalvarResEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarResEspActionPerformed

        String espacodesc = cbEspacoEvento.getSelectedItem().toString();
        if (espacodesc.equals("...")) {
            JOptionPane.showMessageDialog(null, "Espaço não selecionado");
            return;
        }
        String data = tfDataResEsp.getText();
        if (data.length() == 0) {
            JOptionPane.showMessageDialog(null, "Campo data está vazio");
            return;
        }
        String descricao = tfDescricao.getText();
        if (descricao.length() == 0) {
            JOptionPane.showMessageDialog(null, "Campo descricão está vazio");
            return;
        }
        String hora = tfHoraResEsp.getText();
        if (hora.length() == 0) {
            JOptionPane.showMessageDialog(null, "Campo hora está vazio");
            return;
        }

        GerenciadorUsuarios gr = GerenciadorUsuarios.getInstance();
        Usuario usuariologado = gr.getUsuarioLogado();
        GerenciadorEspacos ge = GerenciadorEspacos.getInstance();
        Espaco espaco = ge.buscarEspaco(espacodesc);
        if(espaco == null) {System.out.println("Espaço null");return;}
        GerenciadorReservaEspaco gre = GerenciadorReservaEspaco.getInstance();
        
        boolean reservado = gre.AdicionarReserva(usuariologado, espaco, data, hora, descricao);
        if(reservado == true) {
            JOptionPane.showMessageDialog(null, "Espaço reservado com sucesso!");
        }
        else {
            JOptionPane.showMessageDialog(null, "Já existe reserva neste espaço, para a data e hora indicadas");
        }

        cbEspacoEvento.setSelectedItem("...");
        tfDataResEsp.setText("");
        tfHoraResEsp.setText("");
        tfDescricao.setText("");

    }//GEN-LAST:event_btSalvarResEspActionPerformed

    private void btLimparResEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparResEspActionPerformed

        cbEspacoEvento.setSelectedItem("...");
        tfDataResEsp.setText("");
        tfHoraResEsp.setText("");
        tfDescricao.setText("");
    }//GEN-LAST:event_btLimparResEspActionPerformed

    private void btExcluirResEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirResEspActionPerformed

        JOptionPane.showMessageDialog(null, "Reserva de espaço excluída com sucesso!");
        cbEspacoEvento.setSelectedItem("...");
        tfDataResEsp.setText("");
        tfRespResEsp.setText("");
        tfHoraResEsp.setText("");
        tfDescricao.setText("");
    }//GEN-LAST:event_btExcluirResEspActionPerformed

    private void cbEspacoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEspacoEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEspacoEventoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluirEvt;
    private javax.swing.JButton btExcluirResEsp;
    private javax.swing.JButton btLimparEvt;
    private javax.swing.JButton btLimparResEsp;
    private javax.swing.JButton btSalvarEvt;
    private javax.swing.JButton btSalvarResEsp;
    private javax.swing.JComboBox<String> cbEspacoEvento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDataEvt;
    private javax.swing.JLabel lbDataResEsp;
    private javax.swing.JLabel lbDescEsp;
    private javax.swing.JLabel lbDescEsp1;
    private javax.swing.JLabel lbFoneEvt;
    private javax.swing.JLabel lbHoraEvt;
    private javax.swing.JLabel lbHoraResEsp;
    private javax.swing.JLabel lbRespEvt;
    private javax.swing.JLabel lbRespResEsp;
    private javax.swing.JLabel lbTituloTelaResEsp;
    private javax.swing.JFormattedTextField tfDataEvt;
    private javax.swing.JFormattedTextField tfDataResEsp;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JFormattedTextField tfFoneEvt;
    private javax.swing.JFormattedTextField tfHoraEvt;
    private javax.swing.JFormattedTextField tfHoraResEsp;
    private javax.swing.JTextField tfRespEvt;
    private javax.swing.JTextField tfRespResEsp;
    // End of variables declaration//GEN-END:variables
}
